FROM rustembedded/cross:x86_64-unknown-linux-musl

WORKDIR /app

RUN apt-get update && apt-get install -y curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH=/root/.cargo/bin:$PATH
RUN rustup target add x86_64-unknown-linux-musl

COPY . /app
CMD ["cargo", "build", "--release", "--target", "x86_64-unknown-linux-musl"]
